# Copyright 2023 Andrew Chen Wang
# Copyright 2023 Jacob Hummer
# SPDX-License-Identifier: Apache-2.0

name: GitHub Wiki Action
author: Andrew Chen Wang <acwangpython@gmail.com>
description: 📖 Deploy docs from your source tree to the GitHub wiki
branding:
  icon: book
  color: blue
inputs:
  repository:
    description: >-
      The repository housing the wiki. Use this if you're publishing to a wiki
      that's not the current repository. You can change the GitHub server with
      the github-server-url input. Default is github.repository.
    required: true
    default: ${{ github.repository }}
  token:
    description: >-
      github.token is the default. This token is used when cloning and pushing
      wiki changes.
    required: true
    default: ${{ github.token }}
  path:
    description: >-
      The directory to use for your wiki contents. Default wiki.
    required: true
    default: wiki
  commit-message:
    description: >-
      The message to use when committing new content. Default is 'Update wiki
      github.sha'. You probably don't need to change this, since this only
      applies if you look really closely in your wiki.
    required: true
    default: Update wiki ${{ github.sha }}
  ignore:
    description: >-
      A multiline list of files that should be ignored when committing and
      pushing to the remote wiki. Each line is a pattern like .gitignore. Make
      sure these paths are relative to the path option! The default is none.
    required: true
    default: ""
runs:
  using: composite
  steps:
    - run: '"${GITHUB_ACTION_PATH%/}/index.sh"'
      shell: bash
      env:
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit-message }}
        INPUT_IGNORE: ${{ inputs.ignore }}
