name: GitHub Wiki Action
author: Andrew Chen Wang <acwangpython@gmail.com>
description: This action publishes Wiki pages with a provided directory into your GitHub repository's Wiki.
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  WIKI_DIR:
    description: 'Directory to rsync files to the wiki.'
    required: true
    default: 'wiki/'
  GH_PAT:
    description: 'The GitHub Personal Access Token for this action to use'
    required: true
  GH_MAIL:
    description: 'The email associated with the token.'
    required: true
  GH_NAME:
    description: 'The username associated with the token.'
    required: true
  REPO:
    description: 'The target repository.'
    required: false
  WIKI_PUSH_MESSAGE:
    description: 'The commit message for the wiki commit. Default is the commit to actual repository.'
    required: false
branding:
  icon: tag
  color: blue
