# Copyright 2023 Jacob Hummer
# SPDX-License-Identifier: Apache-2.0
name: Test action
on:
  push:
    branches: "master"
    paths-ignore:
      - .gitignore
      - .gitattributes
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - .gitattributes
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  test-action-clone-dry-run:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          strategy: clone
          dry-run: true
  test-action-init-dry-run:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          strategy: init
          dry-run: true
  test-action-clone-dry-run-no-empty:
    # Expects no commit (unless the wiki test files are changed).
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          strategy: clone
          dry-run: true
          disable-empty-commits: true
  test-action-init-dry-run-no-empty:
    # Expects a commit either way as the init strategy creates an orphan branch.
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          strategy: init
          dry-run: true
          disable-empty-commits: true
  test-action-real:
    concurrency: ${{ github.workflow }}-real
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
