# Copyright 2023 Jacob Hummer
# SPDX-License-Identifier: Apache-2.0
name: Test action
on:
  push:
    branches: "master"
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
concurrency: ${{ github.workflow }}-${{ github.ref_name }}
jobs:
  test-action:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
