# Copyright 2023 Jacob Hummer
# SPDX-License-Identifier: Apache-2.0

name: Test
on:
  push:
    branches: [master]
    paths-ignore:
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test.yml"
  pull_request:
    paths-ignore:
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  test-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@master
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: ./:clone
        uses: ./
        with:
          strategy: clone
          dry-run: true
      - name: ./:init
        uses: ./
        with:
          strategy: init
          dry-run: true
  test-master:
    if: github.ref_name == 'master'
    needs: test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
