# Copyright 2023 Jacob Hummer
# SPDX-License-Identifier: Apache-2.0
name: Test action
on:
  push:
    branches: "master"
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
jobs:
  test-action-clone:
    concurrency: ${{ github.workflow }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
  test-action-init:
    concurrency: ${{ github.workflow }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          strategy: init
