# Copyright 2023 Jacob Hummer
# SPDX-License-Identifier: Apache-2.0

name: Test
on:
  push:
    branches: [main]
    paths:
      - src/**
      - action.yml
      - wiki/**
      - .github/workflows/test.yml
  pull_request:
    branches: [main]
    paths:
      - src/**
      - action.yml
      - wiki/**
      - .github/workflows/test.yml
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          dry-run: true
  test-main:
    if: github.ref_name == 'main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
